dns_server_ip: 192.168.101.10
server_ip: 192.168.101.11

dns_hostname: dns.sno
admin_hostname: root
api_hostname: api.sno
api_int_hostname: api-int.sno
wildcard: apps.sno
server_hostname: server

server_dig: 10
server_sno_dig: 11

domain: fedora.test
forward: forward.test
reverse: reverse.test
reverse_zone: 101.168.192.in-addr.arpa


