server_hostname: server

server_ip: 192.168.101.11

k8s_api_port: 6443
machine_config_port: 22623
ingress_insecure_port: 80
ingress_secure_port: 443
stats_port: 32700

auth: admin:RedH@t322
balance: roundrobin
mode: tcp

ports:
  - 80
  - 443
  - 6443
  - 22623
  - 32700
